// app/lib/stores/__mocks__/workbench.ts
import { atom, map } from 'nanostores';

export const workbenchStore = {
  showWorkbench: atom(false),
  currentView: atom('code'),
  unsavedFiles: atom(new Set<string>()),
  actionAlert: atom(undefined),
  artifacts: map({}),
  previews: map({}),
  files: map({}),
  currentDocument: atom(undefined),
  selectedFile: atom(undefined),
  firstArtifact: undefined,
  filesCount: 0,
  showTerminal: atom(false),
  boltTerminal: atom(undefined),
  alert: atom(undefined),
  clearAlert: () => {},
  toggleTerminal: () => {},
  attachTerminal: () => {},
  attachBoltTerminal: () => {},
  onTerminalResize: () => {},
  setDocuments: () => {},
  setShowWorkbench: () => {},
  setCurrentDocumentContent: () => {},
  setCurrentDocumentScrollPosition: () => {},
  setSelectedFile: () => {},
  saveFile: () => Promise.resolve(),
  saveCurrentDocument: () => Promise.resolve(),
  resetCurrentDocument: () => {},
  saveAllFiles: () => Promise.resolve(),
  getFileModifications: () => [],
  resetAllFileModifications: () => {},
  abortAllActions: () => {},
  setReloadedMessages: () => {},
  addArtifact: () => {},
  updateArtifact: () => {},
  addAction: () => {},
  runAction: () => {},
  downloadZip: () => Promise.resolve(),
  syncFiles: () => Promise.resolve([]),
  pushToGitHub: () => Promise.resolve(''),
  addToExecutionQueue: (callback: () => Promise<void>) => callback(),
};
